---
- hosts: wordpress_nodes
  become: yes
  vars:
    project_name: wordpress-install
    wp_install_directory: /var/www/{{ project_name }}
    dbuser: user_{{ project_name }}
  tasks:
    - include_tasks: tasks/os-dependencies.yml
    - include_tasks: tasks/manage-db.yml
    - include_tasks: tasks/manage-httpd.yml
    - include_tasks: tasks/manage-wp-install.yml
