---
- yum:
    name: MySQL-python
    state: present
- service:
    name: mariadb
    state: started
- name: "Create db"
  mysql_db:
    name: "{{ project_name }}"
    state: present
- name: "Create user"
  mysql_user:
    name: dbuser
    password: 1234
    priv: '*.*:ALL,GRANT'
    state: present
